### ISSUE TITLE
Can't run spring-boot 2.x applications

### ISSUE THREAD

**Issue by reallynasty** [icetan/mavenix#25]
When building a simple Spring Boot 2.X application, the generated jar refuses to start with an error about the date of the Jar:

```
Exception in thread "main" java.time.DateTimeException: Invalid value for MonthOfYear (valid values 1 - 12): 0
	at java.time.temporal.ValueRange.checkValidValue(ValueRange.java:311)
	at java.time.temporal.ChronoField.checkValidValue(ChronoField.java:703)
	at java.time.LocalDate.of(LocalDate.java:267)
	at java.time.LocalDateTime.of(LocalDateTime.java:336)
	at org.springframework.boot.loader.jar.CentralDirectoryFileHeader.decodeMsDosFormatDateTime(CentralDirectoryFileHeader.java:130)
	at org.springframework.boot.loader.jar.CentralDirectoryFileHeader.getTime(CentralDirectoryFileHeader.java:119)
	at org.springframework.boot.loader.jar.JarEntry.<init>(JarEntry.java:58)
	at org.springframework.boot.loader.jar.JarFileEntries.getEntry(JarFileEntries.java:327)
	at org.springframework.boot.loader.jar.JarFileEntries.access$400(JarFileEntries.java:48)
	at org.springframework.boot.loader.jar.JarFileEntries$EntryIterator.next(JarFileEntries.java:378)
	at org.springframework.boot.loader.jar.JarFileEntries$EntryIterator.next(JarFileEntries.java:362)
	at org.springframework.boot.loader.jar.JarFile$2.nextElement(JarFile.java:198)
	at org.springframework.boot.loader.jar.JarFile$2.nextElement(JarFile.java:189)
	at org.springframework.boot.loader.archive.JarFileArchive$EntryIterator.next(JarFileArchive.java:186)
	at org.springframework.boot.loader.archive.JarFileArchive$EntryIterator.next(JarFileArchive.java:171)
	at org.springframework.boot.loader.archive.JarFileArchive.getNestedArchives(JarFileArchive.java:84)
	at org.springframework.boot.loader.ExecutableArchiveLauncher.getClassPathArchives(ExecutableArchiveLauncher.java:70)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:49)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)

```

Steps to reproduce:

1. Clone a sample project : https://github.com/Gerschtli/spring-rest-api
2. Run mvnix-init, mvnix-update and nix-build to follow the process
3. Then run the jar from the result (This one should work)

Notice that the pom.xml references Spring Boot starter parent 1.5.8

4. Now, upgrade this version to latest (or any >= 2.0) 2.1.5
5. Redo step 2
6. Try to start the application, this time you should get the above error.

Apparently, the ZIP files cannot be dated before 1980, but in the store, all files are dated before this date. Classic unix tools don't care (and so does Spring boot 1.5), but Spring boot 2.0 added a check [here](https://github.com/spring-projects/spring-boot/blob/d0b4dab1c82874e450c0e0655fab60598eaa3ce4/spring-boot-project/spring-boot-tools/spring-boot-loader/src/main/java/org/springframework/boot/loader/jar/CentralDirectoryFileHeader.java#L129).

Python build expressions use a variable `SOURCE_DATE_EPOCH` to be able to define this date to someting like 315532800 (1980).

There is also an ongoing discussion here: https://github.com/NixOS/nixpkgs/issues/60446

I don't know exactly what to change or how to get a running jar with spring boot 2

**Comment by icetan** [comment]
Hi @reallynasty, first off I want to say that this is a perfect example in how to write a great issue :smile:

I managed to recreate your problem and using a method from NixOS/nixpkgs#60446 I managed to solve it.

The simplest solution I found was adding the following to `mavenix.buildMaven` in the generated `default.nix`:

```
  nativeBuildInputs = [ (pkgs.ensureNewerSourcesHook { year = "1980"; }) ];
```

Should probably add this to `mavenix.nix` so it's the default behavior.

**Comment by icetan** [comment]
This is now the default behavior in Mavenix 2.1.0: https://github.com/icetan/mavenix/commit/cd32aa01a2a2b39d3587089740b34592ce49abbe

**Comment by reallynasty** [comment]
Thank you very much
